/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.joda.time.LocalTime;

public class App {
    public String getGreeting() {
        return "Hello world.My name is Piyush";
    }

    public static void main(String[] args) {
		LocalTime ct = new LocalTime();
	
		lamp l1 = new lamp();
		lamp l2 = new lamp();

		l1.turnOn();
		l2.turnOff();

		l1.displayStatus();
		l2.displayStatus();
		
		System.out.println("The current local time is:"+ ct);
        System.out.println(new App().getGreeting());
    }
}
